// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accounts.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountListRequest struct {
	GroupFilter          int32    `protobuf:"varint,1,opt,name=group_filter,json=groupFilter,proto3" json:"group_filter,omitempty"`
	Paging               *Paging  `protobuf:"bytes,2,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountListRequest) Reset()         { *m = AccountListRequest{} }
func (m *AccountListRequest) String() string { return proto.CompactTextString(m) }
func (*AccountListRequest) ProtoMessage()    {}
func (*AccountListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{0}
}

func (m *AccountListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountListRequest.Unmarshal(m, b)
}
func (m *AccountListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountListRequest.Marshal(b, m, deterministic)
}
func (m *AccountListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountListRequest.Merge(m, src)
}
func (m *AccountListRequest) XXX_Size() int {
	return xxx_messageInfo_AccountListRequest.Size(m)
}
func (m *AccountListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountListRequest proto.InternalMessageInfo

func (m *AccountListRequest) GetGroupFilter() int32 {
	if m != nil {
		return m.GroupFilter
	}
	return 0
}

func (m *AccountListRequest) GetPaging() *Paging {
	if m != nil {
		return m.Paging
	}
	return nil
}

type Accounts struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Accounts) Reset()         { *m = Accounts{} }
func (m *Accounts) String() string { return proto.CompactTextString(m) }
func (*Accounts) ProtoMessage()    {}
func (*Accounts) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{1}
}

func (m *Accounts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Accounts.Unmarshal(m, b)
}
func (m *Accounts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Accounts.Marshal(b, m, deterministic)
}
func (m *Accounts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Accounts.Merge(m, src)
}
func (m *Accounts) XXX_Size() int {
	return xxx_messageInfo_Accounts.Size(m)
}
func (m *Accounts) XXX_DiscardUnknown() {
	xxx_messageInfo_Accounts.DiscardUnknown(m)
}

var xxx_messageInfo_Accounts proto.InternalMessageInfo

func (m *Accounts) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type Account struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Saldo                float64  `protobuf:"fixed64,4,opt,name=saldo,proto3" json:"saldo,omitempty"`
	NfcChipId            string   `protobuf:"bytes,5,opt,name=nfc_chip_id,json=nfcChipId,proto3" json:"nfc_chip_id,omitempty"`
	Group                *Group   `protobuf:"bytes,6,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{2}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Account) GetSaldo() float64 {
	if m != nil {
		return m.Saldo
	}
	return 0
}

func (m *Account) GetNfcChipId() string {
	if m != nil {
		return m.NfcChipId
	}
	return ""
}

func (m *Account) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

func init() {
	proto.RegisterType((*AccountListRequest)(nil), "api.AccountListRequest")
	proto.RegisterType((*Accounts)(nil), "api.Accounts")
	proto.RegisterType((*Account)(nil), "api.Account")
}

func init() { proto.RegisterFile("accounts.proto", fileDescriptor_e1e7723af4c007b7) }

var fileDescriptor_e1e7723af4c007b7 = []byte{
	// 520 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xdd, 0x6a, 0xd4, 0x40,
	0x14, 0x26, 0xd9, 0x6e, 0x6c, 0x67, 0xff, 0xdc, 0x23, 0x65, 0x43, 0x10, 0x8c, 0x11, 0x21, 0x04,
	0xbb, 0xc1, 0xb5, 0x57, 0x85, 0x2a, 0xd9, 0x16, 0xcb, 0x82, 0x88, 0x64, 0x29, 0x78, 0x21, 0x2c,
	0xd3, 0x64, 0x36, 0x1d, 0x88, 0x99, 0x98, 0x99, 0xd4, 0x0b, 0xf1, 0xc6, 0x47, 0x88, 0x4f, 0xe1,
	0xf3, 0xf8, 0x0a, 0xde, 0xf8, 0x16, 0x92, 0x49, 0x46, 0xb2, 0xee, 0x85, 0x57, 0xe1, 0x7c, 0x3f,
	0xe7, 0x3b, 0x39, 0x27, 0x41, 0x63, 0x1c, 0x45, 0xac, 0xcc, 0x04, 0x9f, 0xe7, 0x05, 0x13, 0x0c,
	0x7a, 0x38, 0xa7, 0xd6, 0x28, 0x49, 0xd9, 0x0d, 0x4e, 0x5b, 0xcc, 0x1a, 0x26, 0x05, 0x2b, 0x73,
	0x55, 0x3d, 0x4c, 0x18, 0x4b, 0x52, 0xe2, 0xe3, 0x9c, 0xfa, 0x38, 0xcb, 0x98, 0xc0, 0x82, 0xb2,
	0x4c, 0xb1, 0xcf, 0xe4, 0x23, 0x3a, 0x49, 0x48, 0x76, 0xc2, 0x3f, 0xe3, 0x24, 0x21, 0x85, 0xcf,
	0x72, 0xa9, 0xd8, 0x57, 0x3b, 0x1f, 0x10, 0x04, 0x4d, 0xfe, 0x1b, 0xca, 0x45, 0x48, 0x3e, 0x95,
	0x84, 0x0b, 0x78, 0x8c, 0x9a, 0xc4, 0xcd, 0x96, 0xa6, 0x82, 0x14, 0xa6, 0x66, 0x6b, 0x6e, 0x3f,
	0x1c, 0x48, 0xec, 0xb5, 0x84, 0xe0, 0x09, 0x32, 0x72, 0x9c, 0xd0, 0x2c, 0x31, 0x75, 0x5b, 0x73,
	0x07, 0x8b, 0xc1, 0x1c, 0xe7, 0x74, 0xfe, 0x4e, 0x42, 0x61, 0x4b, 0x39, 0xa7, 0xe8, 0xb0, 0xed,
	0xce, 0xc1, 0x45, 0x87, 0xea, 0x4d, 0x4d, 0xcd, 0xee, 0xb9, 0x83, 0xc5, 0x50, 0x5a, 0x5a, 0x41,
	0xf8, 0x97, 0x75, 0x7e, 0xe8, 0xe8, 0x5e, 0x8b, 0xc2, 0x23, 0xa4, 0xd3, 0xb8, 0xc9, 0x5f, 0x4e,
	0xaa, 0x60, 0xe8, 0xa1, 0x96, 0xb1, 0x57, 0x97, 0xa1, 0x4e, 0x63, 0x78, 0x8a, 0x0e, 0x32, 0xfc,
	0x91, 0xc8, 0x29, 0x8e, 0x96, 0xd3, 0x2a, 0x18, 0x7b, 0x43, 0x25, 0xa9, 0x89, 0x50, 0xd2, 0x70,
	0x86, 0x06, 0x31, 0xe1, 0x51, 0x41, 0xe5, 0x26, 0xcc, 0x9e, 0x54, 0x9b, 0x55, 0x70, 0xec, 0x3d,
	0x50, 0xea, 0x0e, 0x1f, 0x76, 0xc5, 0xe0, 0xa2, 0x3e, 0xc7, 0x69, 0xcc, 0xcc, 0x03, 0x5b, 0x73,
	0xb5, 0x25, 0x54, 0xc1, 0xc4, 0x1b, 0x29, 0xd7, 0xba, 0x66, 0xc2, 0x46, 0x50, 0xa7, 0x64, 0xdb,
	0x68, 0x13, 0xdd, 0xd2, 0x7c, 0x43, 0x63, 0xb3, 0x2f, 0x53, 0xac, 0x2a, 0x98, 0x79, 0xc7, 0x4a,
	0xff, 0x76, 0x1b, 0xd9, 0x17, 0xb7, 0x34, 0xb7, 0xaf, 0x4b, 0x1a, 0x87, 0x47, 0xd9, 0x36, 0xaa,
	0xab, 0x55, 0x0c, 0xa7, 0xa8, 0x2f, 0xf7, 0x6b, 0x1a, 0x72, 0x9f, 0x48, 0x2e, 0xe7, 0xaa, 0x46,
	0xfe, 0x49, 0x94, 0x58, 0xd8, 0x88, 0x17, 0xbf, 0x75, 0x34, 0x6e, 0x89, 0x35, 0x29, 0xee, 0x68,
	0x44, 0xe0, 0x3d, 0x3a, 0xa8, 0x6f, 0x09, 0xb3, 0xee, 0x7a, 0x3b, 0xd7, 0xb5, 0x46, 0x5d, 0x82,
	0x3b, 0x6e, 0x15, 0x4c, 0xad, 0x89, 0xea, 0xce, 0x9b, 0x2e, 0xdf, 0x7e, 0xfe, 0xfa, 0xae, 0x8f,
	0x61, 0xe8, 0xdf, 0x3d, 0xf7, 0xd5, 0x61, 0xe0, 0x1c, 0x19, 0x17, 0x05, 0xc1, 0x82, 0xc0, 0xce,
	0xe9, 0xac, 0x9d, 0xca, 0x99, 0x49, 0xef, 0xd4, 0xd9, 0xf1, 0x9e, 0x69, 0x1e, 0x9c, 0xa3, 0xde,
	0x15, 0x11, 0x30, 0x96, 0xea, 0x55, 0xac, 0xc6, 0xd9, 0x75, 0x9b, 0xd2, 0x0d, 0x70, 0xbf, 0xe3,
	0xf6, 0xbf, 0xd0, 0xf8, 0x2b, 0xbc, 0x44, 0xc6, 0x75, 0x1e, 0xff, 0x2f, 0xbd, 0xf5, 0x5b, 0xfb,
	0xfe, 0x57, 0xc8, 0xb8, 0x24, 0x29, 0x11, 0x64, 0x6f, 0x82, 0xe6, 0xdb, 0x5d, 0x0b, 0x2c, 0x4a,
	0xae, 0x1a, 0x78, 0x7b, 0x0d, 0x6e, 0x0c, 0xf9, 0xcb, 0xbc, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff,
	0xe8, 0x1b, 0xad, 0xc5, 0xb2, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	List(ctx context.Context, in *AccountListRequest, opts ...grpc.CallOption) (*Accounts, error)
	Create(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Account, error)
	Get(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Account, error)
	Update(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Account, error)
	Delete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Status, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) List(ctx context.Context, in *AccountListRequest, opts ...grpc.CallOption) (*Accounts, error) {
	out := new(Accounts)
	err := c.cc.Invoke(ctx, "/api.AccountService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Create(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/api.AccountService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Get(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/api.AccountService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Update(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/api.AccountService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Delete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/api.AccountService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	List(context.Context, *AccountListRequest) (*Accounts, error)
	Create(context.Context, *Account) (*Account, error)
	Get(context.Context, *IdRequest) (*Account, error)
	Update(context.Context, *Account) (*Account, error)
	Delete(context.Context, *IdRequest) (*Status, error)
}

// UnimplementedAccountServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServiceServer struct {
}

func (*UnimplementedAccountServiceServer) List(ctx context.Context, req *AccountListRequest) (*Accounts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedAccountServiceServer) Create(ctx context.Context, req *Account) (*Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedAccountServiceServer) Get(ctx context.Context, req *IdRequest) (*Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedAccountServiceServer) Update(ctx context.Context, req *Account) (*Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedAccountServiceServer) Delete(ctx context.Context, req *IdRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AccountService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).List(ctx, req.(*AccountListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AccountService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Create(ctx, req.(*Account))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AccountService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Get(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AccountService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Update(ctx, req.(*Account))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AccountService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Delete(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AccountService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _AccountService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AccountService_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AccountService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AccountService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accounts.proto",
}
