// Code generated by protoc-gen-go. DO NOT EDIT.
// source: globals.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_b61bc6eb45b21f34, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Status) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type Paging struct {
	Limit                int32    `protobuf:"varint,1,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Paging) Reset()         { *m = Paging{} }
func (m *Paging) String() string { return proto.CompactTextString(m) }
func (*Paging) ProtoMessage()    {}
func (*Paging) Descriptor() ([]byte, []int) {
	return fileDescriptor_b61bc6eb45b21f34, []int{1}
}

func (m *Paging) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paging.Unmarshal(m, b)
}
func (m *Paging) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paging.Marshal(b, m, deterministic)
}
func (m *Paging) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paging.Merge(m, src)
}
func (m *Paging) XXX_Size() int {
	return xxx_messageInfo_Paging.Size(m)
}
func (m *Paging) XXX_DiscardUnknown() {
	xxx_messageInfo_Paging.DiscardUnknown(m)
}

var xxx_messageInfo_Paging proto.InternalMessageInfo

func (m *Paging) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Paging) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type IdRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdRequest) Reset()         { *m = IdRequest{} }
func (m *IdRequest) String() string { return proto.CompactTextString(m) }
func (*IdRequest) ProtoMessage()    {}
func (*IdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b61bc6eb45b21f34, []int{2}
}

func (m *IdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdRequest.Unmarshal(m, b)
}
func (m *IdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdRequest.Marshal(b, m, deterministic)
}
func (m *IdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdRequest.Merge(m, src)
}
func (m *IdRequest) XXX_Size() int {
	return xxx_messageInfo_IdRequest.Size(m)
}
func (m *IdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdRequest proto.InternalMessageInfo

func (m *IdRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Status)(nil), "api.Status")
	proto.RegisterType((*Paging)(nil), "api.Paging")
	proto.RegisterType((*IdRequest)(nil), "api.IdRequest")
}

func init() { proto.RegisterFile("globals.proto", fileDescriptor_b61bc6eb45b21f34) }

var fileDescriptor_b61bc6eb45b21f34 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xcd, 0x6a, 0xdb, 0x40,
	0x14, 0x85, 0x91, 0x8c, 0xd5, 0x7a, 0xa8, 0x5b, 0x77, 0x28, 0xc5, 0xb8, 0x5d, 0x08, 0x75, 0x63,
	0x8a, 0x25, 0x25, 0x0e, 0x64, 0xe1, 0x55, 0x12, 0x43, 0xfe, 0xc8, 0x1f, 0xf2, 0x03, 0x98, 0xd1,
	0xe8, 0x6a, 0x34, 0x46, 0x9a, 0x51, 0x74, 0x47, 0x31, 0x79, 0x8d, 0xbc, 0x4a, 0x16, 0x79, 0xbd,
	0x90, 0x91, 0xbd, 0xca, 0xee, 0x7e, 0xe7, 0xf2, 0x9d, 0xc5, 0x21, 0x43, 0x51, 0xea, 0x94, 0x95,
	0x18, 0xd5, 0x8d, 0x36, 0x9a, 0xf6, 0x58, 0x2d, 0x27, 0x33, 0x7b, 0xf3, 0x50, 0x80, 0x0a, 0x71,
	0xcb, 0x84, 0x80, 0x26, 0xd6, 0xb5, 0x91, 0x5a, 0x61, 0xcc, 0x94, 0xd2, 0x86, 0xd9, 0xbb, 0x53,
	0x82, 0x0b, 0xe2, 0xad, 0x0c, 0x33, 0x2d, 0xd2, 0x31, 0xf9, 0x82, 0x2d, 0xe7, 0x80, 0x38, 0x76,
	0x7c, 0x67, 0xfa, 0x35, 0xd9, 0x23, 0xfd, 0x47, 0x86, 0xd0, 0x34, 0xba, 0x59, 0x57, 0x80, 0xc8,
	0x04, 0x8c, 0x5d, 0xdf, 0x99, 0x0e, 0x92, 0x6f, 0x36, 0xbc, 0xed, 0xb2, 0xe0, 0x98, 0x78, 0x0f,
	0x4c, 0x48, 0x25, 0xe8, 0x2f, 0xd2, 0xbf, 0x91, 0x95, 0x34, 0xb6, 0xa6, 0x9f, 0x74, 0x40, 0x7f,
	0x13, 0xef, 0x3e, 0xcf, 0x11, 0x8c, 0xb5, 0xfb, 0xc9, 0x8e, 0x82, 0x3f, 0x64, 0x70, 0x95, 0x25,
	0xf0, 0xd8, 0x02, 0x1a, 0xfa, 0x9d, 0xb8, 0x32, 0xdb, 0x79, 0xae, 0xcc, 0xce, 0xde, 0x9c, 0x97,
	0xd3, 0x57, 0x87, 0x6e, 0xc9, 0x8f, 0xbb, 0xf3, 0xa5, 0xbf, 0x64, 0x58, 0xf8, 0xab, 0x67, 0x34,
	0x50, 0x05, 0x6b, 0xf2, 0xf3, 0x5a, 0x17, 0x4c, 0x29, 0x40, 0xff, 0x12, 0x64, 0x95, 0x32, 0x5e,
	0xd0, 0x59, 0x61, 0x4c, 0x8d, 0x8b, 0x38, 0x16, 0xd2, 0x14, 0x6d, 0x1a, 0x71, 0x5d, 0xc5, 0x9b,
	0x62, 0xf7, 0x8d, 0x55, 0xce, 0x43, 0xce, 0xb0, 0x08, 0xd1, 0x56, 0x4c, 0xfe, 0xaa, 0x9c, 0x7f,
	0x70, 0x87, 0x27, 0x15, 0x64, 0x12, 0x14, 0x1a, 0x56, 0x9a, 0x28, 0x83, 0x79, 0xef, 0x30, 0x3a,
	0x98, 0x8c, 0xf6, 0x4e, 0x04, 0x4f, 0x9b, 0x3a, 0xca, 0xe0, 0xbf, 0xeb, 0xb8, 0xf3, 0x11, 0xab,
	0xeb, 0x52, 0x72, 0xbb, 0x63, 0xbc, 0x41, 0xad, 0x16, 0x9f, 0x92, 0xd4, 0xb3, 0xf3, 0x1e, 0xbd,
	0x07, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x39, 0x0c, 0x91, 0xa2, 0x01, 0x00, 0x00,
}
