// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transactions.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionAllRequest struct {
	Paging               *Paging  `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionAllRequest) Reset()         { *m = TransactionAllRequest{} }
func (m *TransactionAllRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionAllRequest) ProtoMessage()    {}
func (*TransactionAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b72849cf10e9c77, []int{0}
}

func (m *TransactionAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionAllRequest.Unmarshal(m, b)
}
func (m *TransactionAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionAllRequest.Marshal(b, m, deterministic)
}
func (m *TransactionAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionAllRequest.Merge(m, src)
}
func (m *TransactionAllRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionAllRequest.Size(m)
}
func (m *TransactionAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionAllRequest proto.InternalMessageInfo

func (m *TransactionAllRequest) GetPaging() *Paging {
	if m != nil {
		return m.Paging
	}
	return nil
}

type TransactionListRequest struct {
	AccountId            int32    `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Paging               *Paging  `protobuf:"bytes,2,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionListRequest) Reset()         { *m = TransactionListRequest{} }
func (m *TransactionListRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionListRequest) ProtoMessage()    {}
func (*TransactionListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b72849cf10e9c77, []int{1}
}

func (m *TransactionListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionListRequest.Unmarshal(m, b)
}
func (m *TransactionListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionListRequest.Marshal(b, m, deterministic)
}
func (m *TransactionListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionListRequest.Merge(m, src)
}
func (m *TransactionListRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionListRequest.Size(m)
}
func (m *TransactionListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionListRequest proto.InternalMessageInfo

func (m *TransactionListRequest) GetAccountId() int32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *TransactionListRequest) GetPaging() *Paging {
	if m != nil {
		return m.Paging
	}
	return nil
}

type TransactionRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId            int32    `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionRequest) Reset()         { *m = TransactionRequest{} }
func (m *TransactionRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionRequest) ProtoMessage()    {}
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b72849cf10e9c77, []int{2}
}

func (m *TransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRequest.Unmarshal(m, b)
}
func (m *TransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRequest.Marshal(b, m, deterministic)
}
func (m *TransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRequest.Merge(m, src)
}
func (m *TransactionRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionRequest.Size(m)
}
func (m *TransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRequest proto.InternalMessageInfo

func (m *TransactionRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TransactionRequest) GetAccountId() int32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type Transactions struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Transactions) Reset()         { *m = Transactions{} }
func (m *Transactions) String() string { return proto.CompactTextString(m) }
func (*Transactions) ProtoMessage()    {}
func (*Transactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b72849cf10e9c77, []int{3}
}

func (m *Transactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transactions.Unmarshal(m, b)
}
func (m *Transactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transactions.Marshal(b, m, deterministic)
}
func (m *Transactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transactions.Merge(m, src)
}
func (m *Transactions) XXX_Size() int {
	return xxx_messageInfo_Transactions.Size(m)
}
func (m *Transactions) XXX_DiscardUnknown() {
	xxx_messageInfo_Transactions.DiscardUnknown(m)
}

var xxx_messageInfo_Transactions proto.InternalMessageInfo

func (m *Transactions) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type Transaction struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OldSaldo             float64              `protobuf:"fixed64,2,opt,name=old_saldo,json=oldSaldo,proto3" json:"old_saldo,omitempty"`
	NewSaldo             float64              `protobuf:"fixed64,3,opt,name=new_saldo,json=newSaldo,proto3" json:"new_saldo,omitempty"`
	Amount               float64              `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created,proto3" json:"created,omitempty"`
	Account              *Account             `protobuf:"bytes,6,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b72849cf10e9c77, []int{4}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Transaction) GetOldSaldo() float64 {
	if m != nil {
		return m.OldSaldo
	}
	return 0
}

func (m *Transaction) GetNewSaldo() float64 {
	if m != nil {
		return m.NewSaldo
	}
	return 0
}

func (m *Transaction) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Transaction) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func init() {
	proto.RegisterType((*TransactionAllRequest)(nil), "api.TransactionAllRequest")
	proto.RegisterType((*TransactionListRequest)(nil), "api.TransactionListRequest")
	proto.RegisterType((*TransactionRequest)(nil), "api.TransactionRequest")
	proto.RegisterType((*Transactions)(nil), "api.Transactions")
	proto.RegisterType((*Transaction)(nil), "api.Transaction")
}

func init() { proto.RegisterFile("transactions.proto", fileDescriptor_0b72849cf10e9c77) }

var fileDescriptor_0b72849cf10e9c77 = []byte{
	// 471 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x51, 0x6b, 0xd4, 0x40,
	0x10, 0x26, 0x49, 0x9b, 0xda, 0xb9, 0xb3, 0xd4, 0x11, 0x6b, 0x48, 0x15, 0x4b, 0x44, 0x2d, 0x87,
	0x26, 0x7a, 0xf6, 0x49, 0x7c, 0x39, 0x2a, 0x88, 0x20, 0x22, 0x69, 0x1f, 0xc5, 0xb2, 0x97, 0x5d,
	0xc3, 0xc2, 0x5e, 0x36, 0xde, 0xee, 0xb5, 0x0f, 0xa5, 0x2f, 0xfe, 0x04, 0xfd, 0x5d, 0x3e, 0xf9,
	0x17, 0xfc, 0x21, 0x92, 0xbd, 0x8d, 0xb7, 0x4d, 0x4e, 0xf0, 0x71, 0xe6, 0x9b, 0xf9, 0xbe, 0x99,
	0xf9, 0x06, 0x50, 0xcf, 0x49, 0xa5, 0x48, 0xa1, 0xb9, 0xac, 0x54, 0x5a, 0xcf, 0xa5, 0x96, 0x18,
	0x90, 0x9a, 0xc7, 0x37, 0x4b, 0x21, 0xa7, 0x44, 0xd8, 0x5c, 0xbc, 0x43, 0x8a, 0x42, 0x2e, 0x2a,
	0xdd, 0xc6, 0x0f, 0x4a, 0x29, 0x4b, 0xc1, 0x32, 0x13, 0x4d, 0x17, 0x5f, 0x32, 0xcd, 0x67, 0x4c,
	0x69, 0x32, 0xab, 0x6d, 0xc1, 0x3d, 0x5b, 0x40, 0x6a, 0x9e, 0x91, 0xaa, 0x92, 0x9a, 0x38, 0x12,
	0xc9, 0x6b, 0xb8, 0x73, 0xba, 0x12, 0x9e, 0x08, 0x91, 0xb3, 0xaf, 0x0b, 0xa6, 0x34, 0x3e, 0x84,
	0xb0, 0x26, 0x25, 0xaf, 0xca, 0xc8, 0x3b, 0xf0, 0x0e, 0x07, 0xe3, 0x41, 0x4a, 0x6a, 0x9e, 0x7e,
	0x34, 0xa9, 0xdc, 0x42, 0xc9, 0x27, 0xd8, 0x73, 0xba, 0xdf, 0x73, 0xa5, 0xdb, 0xf6, 0xfb, 0x00,
	0x76, 0xd0, 0x33, 0x4e, 0x0d, 0xc5, 0x66, 0xbe, 0x6d, 0x33, 0xef, 0xa8, 0xc3, 0xee, 0xff, 0x9b,
	0xfd, 0x18, 0xd0, 0x61, 0x6f, 0x99, 0x77, 0xc0, 0xff, 0xcb, 0xe8, 0x73, 0xda, 0x51, 0xf2, 0x3b,
	0x4a, 0xc9, 0x1b, 0x18, 0x3a, 0x24, 0x0a, 0x8f, 0x60, 0xe8, 0x5e, 0x3a, 0xf2, 0x0e, 0x82, 0xc3,
	0xc1, 0x78, 0xd7, 0xe8, 0xbb, 0x6a, 0xd7, 0xaa, 0x92, 0x9f, 0x1e, 0x0c, 0x1c, 0xb4, 0x37, 0xc4,
	0x3e, 0x6c, 0x4b, 0x41, 0xcf, 0x14, 0x11, 0x54, 0x9a, 0x19, 0xbc, 0xfc, 0x86, 0x14, 0xf4, 0xa4,
	0x89, 0x1b, 0xb0, 0x62, 0x17, 0x16, 0x0c, 0x96, 0x60, 0xc5, 0x2e, 0x96, 0xe0, 0x1e, 0x84, 0x64,
	0xd6, 0xcc, 0x1a, 0x6d, 0x18, 0xc4, 0x46, 0x78, 0x04, 0x5b, 0xc5, 0x9c, 0x11, 0xcd, 0x68, 0xb4,
	0x69, 0x4e, 0x14, 0xa7, 0x4b, 0x23, 0xd3, 0xd6, 0xe9, 0xf4, 0xb4, 0x75, 0x3a, 0x6f, 0x4b, 0xf1,
	0x31, 0x6c, 0xd9, 0xd5, 0xa3, 0xd0, 0x74, 0x0d, 0xcd, 0x62, 0x93, 0x65, 0x2e, 0x6f, 0xc1, 0xf1,
	0xf7, 0x00, 0x6e, 0xbb, 0x67, 0x39, 0x61, 0xf3, 0x73, 0x5e, 0x30, 0xfc, 0x00, 0xc1, 0x44, 0x08,
	0x8c, 0xbb, 0xe7, 0x58, 0x3d, 0x46, 0x7c, 0xab, 0x8b, 0xa9, 0x24, 0xfa, 0xf6, 0xeb, 0xf7, 0x0f,
	0x1f, 0x71, 0x37, 0x3b, 0x7f, 0x91, 0xb9, 0x77, 0x43, 0x06, 0x1b, 0xcd, 0x57, 0xe0, 0x7e, 0xb7,
	0xc9, 0xf9, 0x95, 0x75, 0x8c, 0xcf, 0x0c, 0xe3, 0x13, 0x7c, 0xd4, 0x30, 0xda, 0xa1, 0xb3, 0xcb,
	0x95, 0xcf, 0x57, 0xd7, 0x65, 0x3e, 0x43, 0x78, 0x6c, 0x2e, 0x80, 0x3d, 0x23, 0xe3, 0x5e, 0x26,
	0x79, 0x6e, 0xc8, 0x47, 0xc9, 0x5a, 0xf2, 0xb4, 0x4b, 0xfe, 0xca, 0x1b, 0x21, 0x85, 0xe0, 0x2d,
	0xd3, 0x78, 0xb7, 0xf7, 0x25, 0x76, 0x83, 0xbe, 0xc6, 0xd8, 0x68, 0x3c, 0xc5, 0xd1, 0x7f, 0x2d,
	0x90, 0x5d, 0x72, 0x7a, 0x35, 0x0d, 0x8d, 0xb3, 0x2f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe2,
	0x36, 0x63, 0x6f, 0x0b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransactionsServiceClient is the client API for TransactionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionsServiceClient interface {
	All(ctx context.Context, in *TransactionAllRequest, opts ...grpc.CallOption) (*Transactions, error)
	List(ctx context.Context, in *TransactionListRequest, opts ...grpc.CallOption) (*Transactions, error)
	Create(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Transaction, error)
	Get(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*Transaction, error)
}

type transactionsServiceClient struct {
	cc *grpc.ClientConn
}

func NewTransactionsServiceClient(cc *grpc.ClientConn) TransactionsServiceClient {
	return &transactionsServiceClient{cc}
}

func (c *transactionsServiceClient) All(ctx context.Context, in *TransactionAllRequest, opts ...grpc.CallOption) (*Transactions, error) {
	out := new(Transactions)
	err := c.cc.Invoke(ctx, "/api.TransactionsService/All", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionsServiceClient) List(ctx context.Context, in *TransactionListRequest, opts ...grpc.CallOption) (*Transactions, error) {
	out := new(Transactions)
	err := c.cc.Invoke(ctx, "/api.TransactionsService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionsServiceClient) Create(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := c.cc.Invoke(ctx, "/api.TransactionsService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionsServiceClient) Get(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := c.cc.Invoke(ctx, "/api.TransactionsService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionsServiceServer is the server API for TransactionsService service.
type TransactionsServiceServer interface {
	All(context.Context, *TransactionAllRequest) (*Transactions, error)
	List(context.Context, *TransactionListRequest) (*Transactions, error)
	Create(context.Context, *Transaction) (*Transaction, error)
	Get(context.Context, *TransactionRequest) (*Transaction, error)
}

// UnimplementedTransactionsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTransactionsServiceServer struct {
}

func (*UnimplementedTransactionsServiceServer) All(ctx context.Context, req *TransactionAllRequest) (*Transactions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method All not implemented")
}
func (*UnimplementedTransactionsServiceServer) List(ctx context.Context, req *TransactionListRequest) (*Transactions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedTransactionsServiceServer) Create(ctx context.Context, req *Transaction) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedTransactionsServiceServer) Get(ctx context.Context, req *TransactionRequest) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterTransactionsServiceServer(s *grpc.Server, srv TransactionsServiceServer) {
	s.RegisterService(&_TransactionsService_serviceDesc, srv)
}

func _TransactionsService_All_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionsServiceServer).All(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TransactionsService/All",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionsServiceServer).All(ctx, req.(*TransactionAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionsService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionsServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TransactionsService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionsServiceServer).List(ctx, req.(*TransactionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionsService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionsServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TransactionsService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionsServiceServer).Create(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionsService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionsServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TransactionsService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionsServiceServer).Get(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransactionsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.TransactionsService",
	HandlerType: (*TransactionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "All",
			Handler:    _TransactionsService_All_Handler,
		},
		{
			MethodName: "List",
			Handler:    _TransactionsService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _TransactionsService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TransactionsService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transactions.proto",
}
