// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserLogin struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLogin) Reset()         { *m = UserLogin{} }
func (m *UserLogin) String() string { return proto.CompactTextString(m) }
func (*UserLogin) ProtoMessage()    {}
func (*UserLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{0}
}

func (m *UserLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLogin.Unmarshal(m, b)
}
func (m *UserLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLogin.Marshal(b, m, deterministic)
}
func (m *UserLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLogin.Merge(m, src)
}
func (m *UserLogin) XXX_Size() int {
	return xxx_messageInfo_UserLogin.Size(m)
}
func (m *UserLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLogin.DiscardUnknown(m)
}

var xxx_messageInfo_UserLogin proto.InternalMessageInfo

func (m *UserLogin) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type User struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func init() {
	proto.RegisterType((*UserLogin)(nil), "api.UserLogin")
	proto.RegisterType((*User)(nil), "api.User")
}

func init() { proto.RegisterFile("users.proto", fileDescriptor_030765f334c86cea) }

var fileDescriptor_030765f334c86cea = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0xbd, 0xce, 0x82, 0x30,
	0x14, 0x86, 0xc3, 0xdf, 0xf7, 0xc9, 0x21, 0x71, 0x68, 0x1c, 0x08, 0x8b, 0x84, 0x89, 0xa9, 0x24,
	0xea, 0xea, 0x1d, 0x38, 0x11, 0xbd, 0x80, 0x62, 0x8f, 0xa4, 0x09, 0xa5, 0x4d, 0x5b, 0xf4, 0xf6,
	0x8d, 0x45, 0xd4, 0xed, 0xbc, 0xe7, 0xfd, 0xc9, 0x03, 0xd9, 0x64, 0xd1, 0x58, 0xaa, 0x8d, 0x72,
	0x8a, 0x44, 0x4c, 0x8b, 0x62, 0xdb, 0x2b, 0xd5, 0x0f, 0xd8, 0xf8, 0x57, 0x37, 0xdd, 0x1a, 0x27,
	0x24, 0x5a, 0xc7, 0xa4, 0x9e, 0x53, 0xd5, 0x11, 0xd2, 0x8b, 0x45, 0x73, 0x52, 0xbd, 0x18, 0xc9,
	0x06, 0x12, 0x94, 0x4c, 0x0c, 0x79, 0x50, 0x06, 0x75, 0xda, 0xce, 0x82, 0x14, 0xb0, 0xd2, 0xcc,
	0xda, 0x87, 0x32, 0x3c, 0x0f, 0xbd, 0xf1, 0xd1, 0xd5, 0x1d, 0xe2, 0x57, 0x9d, 0xac, 0x21, 0x14,
	0xdc, 0xd7, 0x92, 0x36, 0x14, 0x9c, 0x10, 0x88, 0x47, 0x26, 0xf1, 0x9d, 0xf7, 0xf7, 0x77, 0x3d,
	0xfa, 0x5d, 0x3f, 0xc0, 0xff, 0xd5, 0x20, 0x73, 0xc8, 0xf3, 0xb8, 0x0c, 0xea, 0x6c, 0x57, 0xd0,
	0x99, 0x99, 0x2e, 0xcc, 0xf4, 0xbc, 0x30, 0xb7, 0x4b, 0xb4, 0xfb, 0xf3, 0xe6, 0xfe, 0x19, 0x00,
	0x00, 0xff, 0xff, 0x19, 0xd7, 0xe0, 0x97, 0xf2, 0x00, 0x00, 0x00,
}
