version: "3.5"
services:
  gateway:
    build:
      context: .
      dockerfile: docker/gateway.Dockerfile
    networks:
      - server
    ports:
      - 8080
    secrets:
      - source: cert.pem
        target: /run/tls/cert.pem
    depends_on:
      - server
    hostname: ${PROJECT}.local
    environment:
      GATEWAY_TLS_CERT: /run/tls/cert.pem
      GATEWAY_GRPC_HOST: grpc-endpoint
      GATEWAY_GRPC_PORT: 50051
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    networks:
      database:
      server:
        aliases:
          - grpc-endpoint
    ports:
      - 50051
    secrets:
      - source: cert.pem
        target: /run/tls/cert.pem
      - source: key.pem
        target: /run/tls/cert-key.pem
    depends_on:
      - db
    environment:
      SERVER_DATABASE.HOST: ${DB_HOST}
      SERVER_DATABASE.USER: ${DB_USER}
      SERVER_DATABASE.PASSWORD: ${DB_PASSWORD}
      SERVER_DATABASE.NAME: ${DB_NAME}
      SERVER_TLS_CERT: /run/tls/cert.pem
      SERVER_TLS_KEY: /run/tls/cert-key.pem
  db:
    image: mariadb:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306
    networks:
      database:
        aliases:
          - ${DB_HOST}
    hostname: ${DB_HOST}
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
networks:
  database:
  server:

volumes:
  db_data:
  db_test_data:

secrets:
  cert.pem:
    file: ./tls/cert.pem
  key.pem:
    file: ./tls/cert-key.pem