version: "3.5"
services:
  server:
    build:
      context: server
    networks:
      - database
    ports:
      - 8080
      - 50051
      - 40000
    secrets:
      - source: cert.pem
        target: /run/tls/cert.pem
      - source: key.pem
        target: /run/tls/cert-key.pem
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
  db:
    image: mariadb:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306
    networks:
      database:
        aliases:
          - ${DB_HOST}
    hostname: ${DB_HOST}
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
networks:
  database:

volumes:
  db_data:
  db_test_data:

secrets:
  cert.pem:
    file: ./tls/cert.pem
  key.pem:
    file: ./tls/cert-key.pem