// Code generated by protoc-gen-go. DO NOT EDIT.
// source: groups.proto

package api

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListGroupsRequest struct {
	Paging               *Paging  `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupsRequest) Reset()         { *m = ListGroupsRequest{} }
func (m *ListGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*ListGroupsRequest) ProtoMessage()    {}
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6616980d7c5e2870, []int{0}
}

func (m *ListGroupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsRequest.Unmarshal(m, b)
}
func (m *ListGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsRequest.Marshal(b, m, deterministic)
}
func (m *ListGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsRequest.Merge(m, src)
}
func (m *ListGroupsRequest) XXX_Size() int {
	return xxx_messageInfo_ListGroupsRequest.Size(m)
}
func (m *ListGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsRequest proto.InternalMessageInfo

func (m *ListGroupsRequest) GetPaging() *Paging {
	if m != nil {
		return m.Paging
	}
	return nil
}

type CreateGroupRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	CanOverdraw          bool     `protobuf:"varint,3,opt,name=can_overdraw,json=canOverdraw,proto3" json:"can_overdraw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupRequest) Reset()         { *m = CreateGroupRequest{} }
func (m *CreateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGroupRequest) ProtoMessage()    {}
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6616980d7c5e2870, []int{1}
}

func (m *CreateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupRequest.Unmarshal(m, b)
}
func (m *CreateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupRequest.Marshal(b, m, deterministic)
}
func (m *CreateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupRequest.Merge(m, src)
}
func (m *CreateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGroupRequest.Size(m)
}
func (m *CreateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupRequest proto.InternalMessageInfo

func (m *CreateGroupRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateGroupRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateGroupRequest) GetCanOverdraw() bool {
	if m != nil {
		return m.CanOverdraw
	}
	return false
}

type GetGroupRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupRequest) Reset()         { *m = GetGroupRequest{} }
func (m *GetGroupRequest) String() string { return proto.CompactTextString(m) }
func (*GetGroupRequest) ProtoMessage()    {}
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6616980d7c5e2870, []int{2}
}

func (m *GetGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupRequest.Unmarshal(m, b)
}
func (m *GetGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupRequest.Marshal(b, m, deterministic)
}
func (m *GetGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupRequest.Merge(m, src)
}
func (m *GetGroupRequest) XXX_Size() int {
	return xxx_messageInfo_GetGroupRequest.Size(m)
}
func (m *GetGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupRequest proto.InternalMessageInfo

func (m *GetGroupRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteGroupRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGroupRequest) Reset()         { *m = DeleteGroupRequest{} }
func (m *DeleteGroupRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupRequest) ProtoMessage()    {}
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6616980d7c5e2870, []int{3}
}

func (m *DeleteGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupRequest.Unmarshal(m, b)
}
func (m *DeleteGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupRequest.Marshal(b, m, deterministic)
}
func (m *DeleteGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupRequest.Merge(m, src)
}
func (m *DeleteGroupRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupRequest.Size(m)
}
func (m *DeleteGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupRequest proto.InternalMessageInfo

func (m *DeleteGroupRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListGroupsResponse struct {
	Groups               []*Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	TotalCount           int32    `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupsResponse) Reset()         { *m = ListGroupsResponse{} }
func (m *ListGroupsResponse) String() string { return proto.CompactTextString(m) }
func (*ListGroupsResponse) ProtoMessage()    {}
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6616980d7c5e2870, []int{4}
}

func (m *ListGroupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsResponse.Unmarshal(m, b)
}
func (m *ListGroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsResponse.Marshal(b, m, deterministic)
}
func (m *ListGroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsResponse.Merge(m, src)
}
func (m *ListGroupsResponse) XXX_Size() int {
	return xxx_messageInfo_ListGroupsResponse.Size(m)
}
func (m *ListGroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsResponse proto.InternalMessageInfo

func (m *ListGroupsResponse) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *ListGroupsResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type Group struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CanOverdraw          bool     `protobuf:"varint,4,opt,name=can_overdraw,json=canOverdraw,proto3" json:"can_overdraw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_6616980d7c5e2870, []int{5}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Group) GetCanOverdraw() bool {
	if m != nil {
		return m.CanOverdraw
	}
	return false
}

func init() {
	proto.RegisterType((*ListGroupsRequest)(nil), "api.ListGroupsRequest")
	proto.RegisterType((*CreateGroupRequest)(nil), "api.CreateGroupRequest")
	proto.RegisterType((*GetGroupRequest)(nil), "api.GetGroupRequest")
	proto.RegisterType((*DeleteGroupRequest)(nil), "api.DeleteGroupRequest")
	proto.RegisterType((*ListGroupsResponse)(nil), "api.ListGroupsResponse")
	proto.RegisterType((*Group)(nil), "api.Group")
}

func init() { proto.RegisterFile("groups.proto", fileDescriptor_6616980d7c5e2870) }

var fileDescriptor_6616980d7c5e2870 = []byte{
	// 666 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0xbe, 0x4e, 0x9a, 0xdc, 0xe6, 0x38, 0x69, 0x6e, 0xe7, 0x56, 0xbd, 0x91, 0x7b, 0x25, 0xa6,
	0x06, 0xa1, 0xca, 0x6a, 0x13, 0x51, 0x58, 0xa0, 0x8a, 0x05, 0x56, 0x81, 0x6c, 0x90, 0x40, 0xa6,
	0x5d, 0xb0, 0xaa, 0x26, 0xf6, 0xd4, 0x1d, 0xe1, 0xcc, 0x18, 0xcf, 0x38, 0x15, 0x20, 0x58, 0xc0,
	0x02, 0x89, 0xa5, 0x11, 0xef, 0xc0, 0xfb, 0xf0, 0x0a, 0xf0, 0x1e, 0x28, 0x33, 0x4e, 0x71, 0x92,
	0x52, 0x56, 0xf6, 0x9c, 0x1f, 0x7f, 0xdf, 0xf9, 0xce, 0xe7, 0x81, 0x76, 0x9c, 0x89, 0x3c, 0x95,
	0xfd, 0x34, 0x13, 0x4a, 0xa0, 0x3a, 0x49, 0x99, 0xd3, 0x89, 0x13, 0x31, 0x22, 0x49, 0x19, 0x73,
	0xb6, 0x62, 0x21, 0xe2, 0x84, 0x0e, 0xf4, 0x69, 0x94, 0x9f, 0x0e, 0xe8, 0x38, 0x55, 0xaf, 0xca,
	0xe4, 0xff, 0x65, 0x92, 0xa4, 0x6c, 0x40, 0x38, 0x17, 0x8a, 0x28, 0x26, 0xf8, 0xac, 0x75, 0x57,
	0x3f, 0xc2, 0xbd, 0x98, 0xf2, 0x3d, 0x79, 0x4e, 0xe2, 0x98, 0x66, 0x03, 0x91, 0xea, 0x8a, 0xe5,
	0x6a, 0xf7, 0x2e, 0xac, 0x3f, 0x66, 0x52, 0x0d, 0x35, 0xa1, 0x80, 0xbe, 0xcc, 0xa9, 0x54, 0xe8,
	0x3a, 0x34, 0x53, 0x12, 0x33, 0x1e, 0xf7, 0x2c, 0x6c, 0xed, 0xd8, 0xfb, 0x76, 0x9f, 0xa4, 0xac,
	0xff, 0x54, 0x87, 0x82, 0x32, 0xe5, 0x7e, 0xb0, 0x00, 0x1d, 0x66, 0x94, 0x28, 0xaa, 0x9b, 0x67,
	0xbd, 0x08, 0x56, 0x38, 0x19, 0x53, 0xdd, 0xd9, 0x0a, 0xf4, 0x3b, 0xc2, 0x60, 0x47, 0x54, 0x86,
	0x19, 0xd3, 0x34, 0x7a, 0x35, 0x9d, 0xaa, 0x86, 0xd0, 0x36, 0xb4, 0x43, 0xc2, 0x4f, 0xc4, 0x84,
	0x66, 0x51, 0x46, 0xce, 0x7b, 0x75, 0x6c, 0xed, 0xac, 0x06, 0x76, 0x48, 0xf8, 0x93, 0x32, 0x74,
	0xb0, 0x51, 0xf8, 0xeb, 0xd0, 0xf5, 0x3a, 0x1a, 0x4d, 0x03, 0x33, 0xc1, 0xdd, 0x6d, 0xe8, 0x0e,
	0xa9, 0x9a, 0x63, 0xb0, 0x06, 0x35, 0x16, 0x69, 0xfc, 0x46, 0x50, 0x63, 0x91, 0x7b, 0x03, 0xd0,
	0x03, 0x9a, 0xd0, 0x05, 0x9e, 0x8b, 0x55, 0x67, 0x80, 0xaa, 0x42, 0xc8, 0x54, 0x70, 0x49, 0x91,
	0x0b, 0x4d, 0xb3, 0xab, 0x9e, 0x85, 0xeb, 0x3b, 0xf6, 0x3e, 0x68, 0x25, 0xcc, 0x87, 0xca, 0x0c,
	0xba, 0x06, 0xb6, 0x12, 0x8a, 0x24, 0x27, 0xa1, 0xc8, 0xb9, 0xd2, 0xd3, 0x35, 0x02, 0xd0, 0xa1,
	0xc3, 0x69, 0xe4, 0xa0, 0x53, 0xf8, 0x00, 0xab, 0x5e, 0xd3, 0x7c, 0xdb, 0x7d, 0x07, 0x0d, 0xfd,
	0xb6, 0x48, 0xe1, 0x42, 0xba, 0xda, 0xef, 0xa5, 0xab, 0xff, 0x59, 0xba, 0x95, 0x65, 0xe9, 0xda,
	0x85, 0xdf, 0x82, 0xbf, 0x3d, 0x03, 0xbb, 0xff, 0xa3, 0x01, 0x46, 0x44, 0xf9, 0x8c, 0x66, 0x13,
	0x16, 0x52, 0xf4, 0xd5, 0x02, 0xf8, 0x35, 0x3c, 0xda, 0xd4, 0x43, 0x2e, 0xd9, 0xc2, 0xf9, 0x6f,
	0x29, 0x6e, 0x54, 0x72, 0x59, 0xe1, 0x1f, 0x39, 0x77, 0xa6, 0x09, 0x89, 0x49, 0x92, 0x60, 0x23,
	0xcc, 0x2e, 0x0e, 0x09, 0xc7, 0x23, 0x8a, 0x13, 0x36, 0x66, 0x8a, 0x46, 0xf8, 0x9c, 0xa9, 0x33,
	0x6c, 0xdc, 0x83, 0x4b, 0x47, 0x7a, 0xf6, 0xb4, 0xab, 0x6c, 0x18, 0x75, 0xa1, 0x03, 0xad, 0x23,
	0xf1, 0x82, 0x72, 0x3f, 0x57, 0x67, 0xe8, 0xaf, 0xf7, 0xdf, 0xbe, 0x7f, 0xae, 0xb5, 0x11, 0x0c,
	0x26, 0xb7, 0x06, 0xa5, 0xd8, 0xaf, 0xc1, 0xae, 0x98, 0x0e, 0x19, 0x4a, 0xcb, 0x36, 0x74, 0x2a,
	0x8b, 0x72, 0x1f, 0x15, 0x7e, 0xdf, 0xe9, 0x98, 0x22, 0x69, 0xb0, 0xbc, 0xb6, 0x39, 0x9a, 0xd3,
	0xe5, 0xc0, 0x5d, 0xb7, 0x02, 0x7c, 0x60, 0x79, 0xe8, 0xa3, 0x05, 0xab, 0x33, 0xb3, 0xa1, 0x0d,
	0x03, 0x30, 0xef, 0xbd, 0x39, 0xd8, 0xe7, 0x85, 0x7f, 0xdf, 0x71, 0x03, 0xaa, 0xf2, 0x8c, 0x4b,
	0x2c, 0x19, 0x8f, 0x93, 0x12, 0xcf, 0x28, 0x11, 0xb3, 0x09, 0xe5, 0x98, 0x45, 0x5e, 0x6b, 0x48,
	0xd5, 0x55, 0x44, 0xfe, 0x41, 0x6b, 0x17, 0x44, 0x06, 0x6f, 0x58, 0xf4, 0x16, 0x7d, 0xb2, 0xc0,
	0x3e, 0x4e, 0xa3, 0x0b, 0x19, 0x2a, 0xb0, 0x73, 0x14, 0xc2, 0xc2, 0x1f, 0x3a, 0x37, 0x4d, 0x65,
	0x39, 0xf9, 0xae, 0xde, 0xd0, 0x29, 0xa3, 0x49, 0x24, 0xf1, 0x38, 0x97, 0x6a, 0xba, 0x21, 0x49,
	0x79, 0xe4, 0xb5, 0x4d, 0xdd, 0x55, 0x4c, 0xfe, 0x75, 0x16, 0x98, 0x4c, 0x65, 0xf9, 0x62, 0x81,
	0x5d, 0xf9, 0xc1, 0xca, 0x9d, 0x2c, 0xff, 0x72, 0xce, 0x66, 0xdf, 0x5c, 0x5c, 0xfd, 0xd9, 0xad,
	0xd6, 0x7f, 0x38, 0xbd, 0xd5, 0xdc, 0xe3, 0xc2, 0xbf, 0xe7, 0x6c, 0x99, 0x06, 0x79, 0xa9, 0x42,
	0x6d, 0x93, 0xbc, 0x52, 0x24, 0x6f, 0x81, 0xda, 0xa8, 0xa9, 0x61, 0x6e, 0xff, 0x0c, 0x00, 0x00,
	0xff, 0xff, 0x23, 0x40, 0x41, 0xdd, 0x6e, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GroupsServiceClient is the client API for GroupsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GroupsServiceClient interface {
	ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*Group, error)
	GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*Group, error)
	UpdateGroup(ctx context.Context, in *Group, opts ...grpc.CallOption) (*Group, error)
	DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type groupsServiceClient struct {
	cc *grpc.ClientConn
}

func NewGroupsServiceClient(cc *grpc.ClientConn) GroupsServiceClient {
	return &groupsServiceClient{cc}
}

func (c *groupsServiceClient) ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, "/api.GroupsService/ListGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsServiceClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*Group, error) {
	out := new(Group)
	err := c.cc.Invoke(ctx, "/api.GroupsService/CreateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsServiceClient) GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*Group, error) {
	out := new(Group)
	err := c.cc.Invoke(ctx, "/api.GroupsService/GetGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsServiceClient) UpdateGroup(ctx context.Context, in *Group, opts ...grpc.CallOption) (*Group, error) {
	out := new(Group)
	err := c.cc.Invoke(ctx, "/api.GroupsService/UpdateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsServiceClient) DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.GroupsService/DeleteGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupsServiceServer is the server API for GroupsService service.
type GroupsServiceServer interface {
	ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error)
	CreateGroup(context.Context, *CreateGroupRequest) (*Group, error)
	GetGroup(context.Context, *GetGroupRequest) (*Group, error)
	UpdateGroup(context.Context, *Group) (*Group, error)
	DeleteGroup(context.Context, *DeleteGroupRequest) (*empty.Empty, error)
}

// UnimplementedGroupsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGroupsServiceServer struct {
}

func (*UnimplementedGroupsServiceServer) ListGroups(ctx context.Context, req *ListGroupsRequest) (*ListGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGroups not implemented")
}
func (*UnimplementedGroupsServiceServer) CreateGroup(ctx context.Context, req *CreateGroupRequest) (*Group, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (*UnimplementedGroupsServiceServer) GetGroup(ctx context.Context, req *GetGroupRequest) (*Group, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroup not implemented")
}
func (*UnimplementedGroupsServiceServer) UpdateGroup(ctx context.Context, req *Group) (*Group, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (*UnimplementedGroupsServiceServer) DeleteGroup(ctx context.Context, req *DeleteGroupRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroup not implemented")
}

func RegisterGroupsServiceServer(s *grpc.Server, srv GroupsServiceServer) {
	s.RegisterService(&_GroupsService_serviceDesc, srv)
}

func _GroupsService_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServiceServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GroupsService/ListGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServiceServer).ListGroups(ctx, req.(*ListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupsService_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServiceServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GroupsService/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServiceServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupsService_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServiceServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GroupsService/GetGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServiceServer).GetGroup(ctx, req.(*GetGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupsService_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Group)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServiceServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GroupsService/UpdateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServiceServer).UpdateGroup(ctx, req.(*Group))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupsService_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServiceServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GroupsService/DeleteGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServiceServer).DeleteGroup(ctx, req.(*DeleteGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GroupsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.GroupsService",
	HandlerType: (*GroupsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListGroups",
			Handler:    _GroupsService_ListGroups_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _GroupsService_CreateGroup_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _GroupsService_GetGroup_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _GroupsService_UpdateGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _GroupsService_DeleteGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "groups.proto",
}
