name: Tests
on: [push]
jobs:
  server_test:
    name: Server Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Start Docker Container
      env:
        PROJECT: nfc-cash-system
      run: docker-compose up -d db_test

    - name: Run tests
      env:
        RUN_INTEGRATION: 1
        TEST_DB_NAME: nfc-cash-system
        TEST_DB_DSN: "${TEST_DB_NAME}:${TEST_DB_NAME}@tcp(${DB_ADDRESS})/${TEST_DB_NAME}?parseTime=true&multiStatements=true"
      run: DB_ADDRESS=$(docker-compose port db_test 3306) go test -v ./server/...
