name: Tests
on: [push]
jobs:
  server_test:
    name: Server Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Create Mysql Database
        env:
          TEST_DB_NAME: nfc-cash-system
        run: mysql -uroot -proot -e "CREATE DATABASE \`$TEST_DB_NAME\` CHARACTER SET UTF8mb4 COLLATE utf8mb4_bin"

      - name: Run tests
        env:
          RUN_INTEGRATION: 1
          PROJECT: nfc-cash-system
          TEST_DB_NAME: nfc-cash-system
          TEST_DB_DSN: "root:root@tcp/${TEST_DB_NAME}?parseTime=true&multiStatements=true"
        run: go test -v ./server/...
  nfcreader:
    name: NFC Reader Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install nfclib
        run: sudo apt-get install libnfc-dev

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Run tests
        run: go test -v ./nfcreader/...